people/urls.py
from django.conf.urls import patterns, url
from people import views
import question
urlpatterns = patterns('',
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^settings/$', views.profile, name="settings"),
    url(r'^settings/upload_headimage/$', views.upload_headimage, name="upload_headimage"),
    url(r'^settings/delete_headimage/$', views.delete_headimage, name="delete_headimage"),
    url(r'^password/$', views.password, name="password"),
    url(r'^user/(?P<uid>\d+)/$', views.user, name="user"),
    url(r'^user/(?P<uid>\d+)/topics/$', views.user_topics, name="user_topics"),
    url(r'^user/(?P<uid>\d+)/comments/$', views.user_comments, name="user_comments"),
    url(r'^users/$', views.au_top, name="au_top"),
    url(r'^follow/(?P<uid>\d+)/$', views.follow, name="follow"),
    url(r'^unfollow/(?P<uid>\d+)/$', views.un_follow, name="unfollow"),
    url(r'^my/following/$', views.following, name="following"),
    url(r'^my/fav/$', question.views.fav_topic_list, name="faved_topic_list"),
    url(r'^send_verified_email/$', views.send_verified_email, name="send_verified_email"),
    url(r'^email_verified/(?P<uid>\d+)/(?P<token>\w+)/$', views.email_verified, name="email_verified"),
    url(r'^find_password/$', views.find_password, name="find_pass"),
    url(r'^reset_password/(?P<uid>\d+)/(?P<token>\w+)/$', views.first_reset_password, name="first_reset_password"),
    url(r'^reset_password/$', views.reset_password, name="reset_password"),
	)	

pro/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('question.urls', namespace='question')),
    url(r'^', include('people.urls', namespace='user')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
]

question/urls.py
from django.conf.urls import patterns, url
from question import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^recent/?$',views.recent, name='recent'),
	url(r'^node/(?P<node_slug>[\w-]+)/$',views.node,name="node"),
	url(r'^t/(?P<topic_id>\d+)/$', views.topic, name="topic"),
	url(r'^node/([\w-]+)/new/?$',views.new,name='new'),
    url(r'^t/(\d+)/edit/?$',views.edit,name='edit'),
    url(r'^t/(\d+)/reply/?$',views.reply,name='reply'),
    url(r'^t/fav/(?P<topic_id>\d+)/$', views.fav_topic, name="fav_topic"),
    url(r'^t/unfav/(?P<topic_id>\d+)/$', views.unfav_topic, name="unfav_topic"),
	url(r'^notice/?$',views.notice,name='notice'),
	url(r'^notice/(\d+)/delete/?$',views.notice_delete,name='notice_delete'),
	url(r'^about/',views.about,name='about'),
	)

question/models.py
from django.db import models
from people.models import Member as User
from django.db.models.signals import post_save

#类别表
class Category(models.Model):
    name = models.CharField(max_length=100,verbose_name='类别名称')
    def __str__(self):
        return self.name
#节点表
class Node(models.Model):
    name = models.CharField(max_length=100,verbose_name='节点名称')
    slug = models.SlugField(max_length=100,verbose_name='url标识符')
    created_on = models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    updated_on = models.DateTimeField(blank=True, null=True,auto_now=True,verbose_name='更新时间')
    num_topics = models.IntegerField(default=0,verbose_name='主题数')
    category = models.ForeignKey(Category,verbose_name='所属类别')
    def __str__(self):
        return self.name
#主题表
class Topic(models.Model):
    title = models.CharField(max_length=100,verbose_name='标题')
    content = models.TextField(verbose_name='内容')
    node = models.ForeignKey(Node,verbose_name='所属节点')
    author = models.ForeignKey(User,verbose_name='作者')
    num_views = models.IntegerField(default=0,verbose_name='浏览量')
    num_comments = models.IntegerField(default=0,verbose_name='评论数')
    num_favorites = models.IntegerField(default=0,verbose_name='收藏数')
    last_reply = models.ForeignKey(User,related_name='+',verbose_name='最后回复者')
    created_on = models.DateTimeField(auto_now_add=True,verbose_name='发表时间')
    updated_on = models.DateTimeField(blank=True, null=True,verbose_name='更新时间')
    def __str__(self):
        return self.title
#评论表
class Comment(models.Model):
    content = models.TextField(verbose_name='内容')
    author = models.ForeignKey(User,verbose_name='作者')
    topic = models.ForeignKey(Topic,verbose_name='所属主题')
    created_on = models.DateTimeField(auto_now_add=True,verbose_name='评论时间')
    def __str__(self):
        return self.content
#消息通知表
class Notice(models.Model):
    from_user = models.ForeignKey(User,related_name='+',verbose_name='来自用户')   #not to create a backwards relation
    to_user = models.ForeignKey(User,related_name='+',verbose_name='接收用户')
    topic = models.ForeignKey(Topic,null=True)
    content = models.TextField()
    time = models.DateTimeField(auto_now_add=True)
    is_readed = models.BooleanField(default=False)
    is_deleted = models.BooleanField(default=False)
    def __str__(self):
        return self.content
#用户最爱文章
class FavoritedTopic(models.Model):
    user = models.ForeignKey(User, verbose_name="用户")
    topic = models.ForeignKey(Topic, verbose_name="主题")
    #class Meta:
        #unique_together = ('user', 'topic')
    def __str__(self):
        return str(self.id)
#信号捕捉
def create_notice(sender, **kwargs):
    #{'signal': <django.db.models.signals.ModelSignal object at 0x000001A035038080>, 
    #'instance': <Comment: 就是棒>, 
    #'created': True, 
    #'update_fields': None, 
    #'raw': False, 
    #'using': 'default'}
    comment = kwargs['instance']
    if comment.author != comment.topic.author:      # don't create notice when you reply to yourself
        Notice.objects.create(from_user=comment.author,to_user=comment.topic.author,topic=comment.topic,content=comment.content)
#只要是涉及到comment的添加操作都会导致这个信号post_save触发
#关于Comment的信号我们将在处理之前先进行这个函数的判断
#如果评论者不是主题所有者，那么在notice表中把评论消息作为通知存储
#信号的格式为一个字典，其中的instance代表当前触发信号的实例对象
post_save.connect(create_notice, sender=Comment)

question/forms.py
from django import forms
from question.models import Topic, Comment

class TopicForm(forms.ModelForm):
    title = forms.CharField(label='标题',required=True)
    content = forms.CharField(label='内容',required=False)
    def clean_title(self):
        title = self.cleaned_data.get("title").strip()
        if len(title) < 3:
            raise forms.ValidationError("标题太短哦...")
        elif len(title) > 100:
            raise forms.ValidationError("标题太长哦...")
        else:
            return title
    def clean_content(self):
        content = self.cleaned_data.get("content").strip()
        if len(content) > 5000:
            raise forms.ValidationError("正文内容太长哦...")
        else:
            return content
    class Meta:
        model = Topic
        fields = ('title','content')

class ReplyForm(forms.ModelForm):
    content = forms.CharField(label=u'回复',required=False)
    def clean_content(self):
        content = self.cleaned_data.get("content").strip()
        if len(content) == 0:
            raise forms.ValidationError("请输入评论内容...")
        elif len(content) > 800:
            raise forms.ValidationError("评论内容太长哦...")
        else:
            return content
    class Meta:
        model = Comment
        fields = ('content',)

class AboutForm(forms.Form):
    url = forms.CharField(label=u'你要爬取的百度图片链接:',required=False)
    def clean_url(self):
        url = self.cleaned_data.get('url').strip()
        if 'baidu' not in url:
            raise forms.ValidationError("请输入正确的百度云链接...")
        else:
            return url

question/views.py
from django.shortcuts import render_to_response,render,HttpResponseRedirect
from django.db.models import Count
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core.urlresolvers import reverse
from django.utils import timezone
import datetime
from question.models import *
from people.models import Member as User
from question.forms import ReplyForm, TopicForm, AboutForm
from django.db import IntegrityError
import re
from django.contrib import messages
from django.conf import settings
from urllib.request import *
import os 
NUM_TOPICS_PER_PAGE = 10
#主题显示数字
NUM_COMMENT_PER_PAGE = 30

STATICFILES_DIRS = getattr(settings, "STATICFILES_DIRS")
def index(request):
    '''首页'''
    # 主题列表
    topic_list = Topic.objects.all().order_by('-updated_on')[:NUM_TOPICS_PER_PAGE]
    # 节点导航
    nodes = cache.get('index_nodes')
    if not nodes:
        nodes = []
        categor_list = Category.objects.all()
        #print request.path
        for category in categor_list:
            node = {}
            category_nodes = Node.objects.filter(category=category.id)
            node['category_name'] = category.name
            node['category_nodes'] = category_nodes
            nodes.append(node)
        cache.set('index_nodes',nodes,60); #1分钟刷新
    # 今日热议
    hot_topics = cache.get('index_hot_topics')  #取缓存
    if not hot_topics:
        now = timezone.now()
        start = now - datetime.timedelta(hours=23, minutes=59, seconds=59)
        hot_comments = Comment.objects.filter(created_on__gt=start).values(
            'topic').annotate(count=Count('topic')).order_by('-count')[:10]
        hot_topics = []
        for comment in hot_comments:
            topic = Topic.objects.get(id=comment['topic'])
            hot_topics.append(topic)
        cache.set('index_hot_topics',hot_topics,60); #1分钟刷新
    return render(request,"question/index.html",
        {'topic_list':topic_list,'nodes':nodes,'hot_topics':hot_topics}
        )

def recent(request):
    """最近的主题"""
    topic_list = Topic.objects.all().order_by('-created_on')
    paginator = Paginator(topic_list, NUM_TOPICS_PER_PAGE)
    page = request.GET.get('page')

    try:
        topic_list = paginator.page(page)
    except PageNotAnInteger:
    	#Page参数为非整数
        topic_list = paginator.page(1)
        #返回第一页
    except EmptyPage:
    	#第X页没数据
        topic_list = paginator.page(paginator.num_pages)
        #返回最后一页
    return render(request,"question/recent.html",{"topic_list":topic_list})

def node(request,node_slug):
    '''节点页'''
    try:
        node = Node.objects.get(slug=node_slug)
    except Node.DoesNotExist:
        raise Http404
    topic_list = Topic.objects.filter(node=node).order_by('-created_on')
    paginator = Paginator(topic_list, NUM_TOPICS_PER_PAGE)
    page = request.GET.get('page')
    try:
        topic_list = paginator.page(page)
    except PageNotAnInteger:
        topic_list = paginator.page(1)
    except EmptyPage:
        topic_list = paginator.page(paginator.num_pages)
    return render(request,"question/node.html",{"node":node, "topic_list":topic_list})

def topic(request,topic_id):
    '''主题详情'''
    try:
        topic = Topic.objects.get(id=topic_id)
    except Topic.DoesNotExist:
        raise Http404
    #根据文章ID返回文章内容
    topic.num_views += 1
    topic.save()
    #每次视图函数的调用都会使这个文章阅读数加一
    faved_num = FavoritedTopic.objects.filter(topic=topic).count()

    if request.user.is_authenticated():
        try:
            faved_topic = FavoritedTopic.objects.filter(user=request.user, topic=topic).first()
        except (User.DoesNotExist, FavoritedTopic.DoesNotExist):
            faved_topic = None
    #判断用户是否已经收藏
    # Comment
    comment_list = Comment.objects.filter(topic=topic).order_by('created_on')
    paginator = Paginator(comment_list, NUM_COMMENT_PER_PAGE)
    page = request.GET.get('page')
    if page == None:
        page = paginator.num_pages
    try:
        comment_list = paginator.page(page)
    except PageNotAnInteger:
        comment_list = paginator.page(1)
    except EmptyPage:
        comment_list = paginator.page(paginator.num_pages)

    form = ReplyForm()
    return render(request,"question/topic.html", locals())
    
def about(request):
    if request.method == 'POST':
        form = AboutForm(request.POST)
        if form.is_valid():
            url = form.cleaned_data['url']
            obj = urlopen(url).read().decode()
            urls = re.findall(r'"objURL":"(.*?)"',obj)
            index = 0
            for url in urls:
                if index <=6:
                    try:
                        print('Downloading...%d'%(index))
                        urlretrieve(url,STATICFILES_DIRS[0]+'/img/'+str(index)+'.png')
                        index += 1
                    except Exception:
                        print('Downloading Failed%d'%(index))
                    finally:
                        print('Downloading Complete')
                else:
                    break
            return render(request,'question/about.html',{'form':form})
    else:
        form = AboutForm()
    return render(request,'question/about.html',{'form':form})

@login_required
def reply(request, topic_id):

    try:
        topic = Topic.objects.get(id=topic_id)
        # comment ---
        comment_list = Comment.objects.filter(topic=topic).order_by('created_on')
        paginator = Paginator(comment_list, NUM_COMMENT_PER_PAGE)
        page = request.GET.get('page')
        if page == None:
            page = paginator.num_pages
        try:
            comment_list = paginator.page(page)
        except PageNotAnInteger:
            comment_list = paginator.page(1)
        except EmptyPage:
            comment_list = paginator.page(paginator.num_pages)
        # comment ---
    except Topic.DoesNotExist:
        raise Http404

    if request.method == 'POST':
        form = ReplyForm(request.POST)
        if form.is_valid():
            last_comment = Comment.objects.filter(author=request.user).order_by('-created_on')[:1]
            last_comment = last_comment.first()
            if last_comment and last_comment.content == form.cleaned_data['content'] and ((timezone.now()-last_comment.created_on).seconds < 5):
                #在以前版本的Django 中，要求 form.clean() 返回 cleaned_data 的一个字典。
                #现在，这个方法仍然可以返回将要用到的数据的字典，但是不再是强制的。
                messages.error(request,'你是否正在尝试连续提交两次相同的回复？');
            else:
                comment = form.save(commit=False)
                request.user.comment_num += 1
                request.user.calculate_au()
                request.user.save()
                comment.author = request.user

                try:
                    topic = Topic.objects.get(id=topic_id)
                except Topic.DoesNotExist:
                    raise Http404

                comment.topic = topic
                comment.save()

                # --- 解析@ ---

                #team_name_pattern = re.compile('(?<=@)(\w+)', re.UNICODE)
                team_name_pattern = re.compile('(?<=@)([0-9a-zA-Z_.]+)', re.UNICODE)
                at_name_list = set(re.findall(team_name_pattern, comment.content))
                if at_name_list:
                    for at_name in at_name_list:
                        if at_name != comment.author.username and at_name != comment.topic.author.username:
                            try:
                                at_user = User.objects.get(username=at_name)
                                if at_user:
                                    notice = Notice(from_user=comment.author,to_user=at_user
                                        ,topic=comment.topic,content=comment.content)
                                    notice.save()
                            except:
                                pass

                # --- 解析@ ---

                topic.num_comments += 1
                topic.updated_on = timezone.now()
                topic.last_reply = request.user
                topic.save()
                return HttpResponseRedirect(reverse("question:topic" ,args=(topic_id,)))
    else:
        form = ReplyForm()

    return render(request,"question/topic.html",{"node":node,
        "topic":topic,"form":form,"comment_list":comment_list,'paginator':paginator})

@login_required
def new(request, node_slug):
    """新主题"""
    #context = {}
    try:
        node = Node.objects.get(slug=node_slug)
    except Node.DoesNotExist:
        raise Http404
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            last_topic = Topic.objects.filter(author=request.user).order_by('-created_on')[:1]
            last_topic = last_topic.first()
            if last_topic and last_topic.title == form.cleaned_data['title'] and ((timezone.now()-last_topic.created_on).seconds < 5):
                messages.error(request,'你是否正在尝试连续提交两次相同的内容？');
                return HttpResponseRedirect(reverse("question:topic" ,args=(last_topic.id,)))
            else:
                topic = form.save(commit=False)
                topic.node = node
                request.user.topic_num += 1
                request.user.calculate_au()
                request.user.save()
                topic.author = request.user
                topic.last_reply = request.user
                topic.updated_on = timezone.now()
                topic.save()
                node.num_topics += 1
                node.save()

                # --- 解析@ ---
                team_name_pattern = re.compile('(?<=@)(\w+)', re.UNICODE)
                at_name_list = set(re.findall(team_name_pattern, topic.content))
                if at_name_list:
                    for at_name in at_name_list:
                        if at_name != topic.author.username:
                            try:

templates/question/edit.html
{% extends "base.html" %}
{% block title %}主题编辑 - {% endblock %}
{% block content %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <ol class="breadcrumb">
                        <li><a href="/">首页</a></li>
                        <li><a href="{% url 'question:node' topic.node.slug %}">{{topic.node.name}}</a></li>
                        <li><a href="{% url 'question:topic' topic.id %}">{{topic.title}}</a></li>
                        <li>编辑</li>
                    </ol>
                </div>
                <div class="panel-body">
                    {% if form.title.errors or form.content.errors %}
                    <div>
                        <ol class="alert alert-danger">
                        遇到问题了：
                        {% for field in form %}
                          {% for error in field.errors %}
                            <li style="margin-left:30px;">{{ error }}</li>
                          {% endfor %}
                        {% endfor %}
                        </ol>
                    </div>
                    {% endif %}
                    <form role="form" action="{% url 'question:edit' topic.id %}" method="post" class="form-vertical">
                      {% csrf_token %}

                      <div class="form-group">
                        <label >{{ form.title.label }}:</label>
                        <input type="text" class="form-control" name="{{ form.title.html_name }}" value="{{ form.title.value |default_if_none:""}}">
                      </div>
                      <div class="form-group">
                        <label>{{ form.content.label }}:</label>
                          <textarea name="content" id="content" class="form-control" rows="10">{{ form.content.value |default_if_none:""}}</textarea>
                      </div>

                      <button type="submit" class="btn btn-default" data-loading-text="正在提交...">编辑</button>
                    </form>
                  </div>
                </br>
                  <blockquote>
                    <small>你可以使用Markdown语法</small>
                  </blockquote>
              </div>
{% endblock %}

{% block sidebar %}
<div class="panel panel-default">
    <div class="panel-heading">Markdown 快速参考</div>
    <div class="panel-body">
      <ul>
        <li>http://example.org 自动加链接</li>
        <li>**粗体**</li>
        <li>~~删除线~~、</li>
        <li>`单行代码`</li>
        <li>```多行代码```</li>
        <li>![图片 Alt text](http://url.com/img.jpg)</li>
      </ul>
    </div>
</div>
{% endblock %}

templates/question/fav_topic.html
{% extends "base.html" %}

{% block title %}收藏列表 - {% endblock %}

{% load questiontag %}
{% load gravatar %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">收藏列表</div>
    <div class="panel-body tableview">
        {% for faved in faved_topic %}
                      <div class="cell">
                          <div class="pull-left">
                              <a href="{% url 'user:user' faved.topic.author.id %}" title="{{ faved.topic.author }}">
                                  <img width="48" height="48" class="headimage" src="{% gravatar faved.topic.author 48 %}">
                              </a>
                          </div>
                          <div class="detail">
                              <div class="pull-right">
                                  <div class="badge badge-info">
                                      <a href="{% url 'question:topic' faved.topic.id %}">
                                          {{ faved.topic.num_comments }}
                                      </a>
                                  </div>
                              </div>
                              <a href="{% url 'question:topic' faved.topic.id %}" class="title">
                                  {{faved.topic.title}}
                              </a>
                              <div class="meta">
                                  <a href="{% url 'question:node' faved.topic.node.slug %}" class="node">
                                      {{ faved.topic.node.name }}
                                  </a>
                                  <span class="text-muted">
                                      •
                                  </span>
                                  <a href="{% url 'user:user' faved.topic.author.id %}" title="{{ faved.topic.author }}">
                                      {{ faved.topic.author }}
                                  </a>
                                  <span class="text-muted">
                                      •
                                  </span>
                                  {{ faved.topic.created_on|time_to_now }}
                                  <span class="text-muted">
                                      •
                                  </span>
                                  最后回复来自
                                  <a href="{% url 'user:user' faved.topic.last_reply.id %}"  title="{{ faved.topic.last_reply }}">
                                      {{ faved.topic.last_reply }}  
                                  </a>
                              </div>
                          </div>
                      </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/question/topic.html
{% extends "base.html" %}
<!-- 主题详情页 -->
{% block title %}{{ topic.title }} - {% endblock %}

{% load gravatar %}
{% load questiontag %}
{% block content %}
<div class="panel panel-default">

  <div class="topic-header">
    <div class="topic-headimg pull-right">
      <a href="{% url 'user:user' topic.author.id %}"><img height="48" width="48" src="{% gravatar topic.author 48 %}" /> 
      </a>   
    </div>
    <div class="topic_breadcrumb">
      <a href="/">主站点</a>  ›   
      <a href="{% url 'question:node' topic.node.slug %}">{{ topic.node }}</a>
    </div>
    <div class="topic-title">{{ topic.title }}
    </div>
    <div class="topic-meta text-muted">
      By 
      <a href="{% url 'user:user' topic.author.id %}">
        {{ topic.author.username }}
      </a> 
      · {{ topic.created_on|time_to_now }} · {{ topic.num_views }} 次点击 · {{ faved_num }} 人收藏
      {% if user.is_authenticated %}
        {% if user.id == topic.author.id %}
          · <a href="{% url 'question:edit' topic.id %}" class="node">编辑</a>
        {% endif %}
      {% endif %}
    </div>
  </div>

  <div class="panel-body">
    {{ topic.content|my_markdown:"topic" }}
  </div>
  <div class="panel-footer topic-footer">
    {% if user.is_authenticated %}
      {% if user.id != topic.author.id %}
        <div class="pull-left">
          {% if not faved_topic %}
            <form action="{% url 'question:fav_topic' topic.id %}" method="POST">
              {% csrf_token %}
            <button class="btn btn-default fav-btn" type="submit">加入收藏</button>
          </form>
          {% else %}
            <form action="{% url 'question:unfav_topic' topic.id %}" method="POST">
              {% csrf_token %}
            <button class="btn btn-default fav-btn" type="submit">取消收藏</button>
          </form>
          {% endif %}
      </div>
      {% endif %}
    {% endif %}

    <!-- Share -->
    <div class="pull-right">
      <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_twi" data-cmd="twi" title="分享到Twitter"></a><a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a><a href="#" class="bds_copy" data-cmd="copy" title="分享到复制网址"></a>
      </div>
    </div>
    <div class="clearfix">
    </div>
    <!-- Share -->
  </div>
</div>

{% endblock %}


{% block reply %}
<div class="panel panel-default">
  <div class="panel-heading">{{ comment_list.count }} 回复</div>
  <div class="panel-body comment-tableview">
    {% for comment in comment_list %}
      {% include "question/topic_comments_cell.html" %}
    {% endfor %}
  </div>  
  {% if comment_list.paginator.num_pages > 1 %}
    <div class="panel-footer">
      <ul class="pager text-muted">

        {% if comment_list.has_previous %}
          <li class="previous">
            <a href="?page={{ comment_list.previous_page_number }}">&larr;上一页</a>
          </li>
        {% else %}
          <li class="previous disabled">
            <a href="#">&larr;上一页</a>
          </li>
        {% endif %}

        <li>{{ comment_list.number }}/{{ comment_list.paginator.num_pages }}</li>

        {% if comment_list.has_next %}
          <li class="next">
            <a href="?page={{ comment_list.next_page_number }}">下一页 &rarr;</a>
          </li>
        {% else %}
          <li class="next disabled">
            <a href="#">下一页 &rarr;</a>
          </li>
        {% endif %}
      </ul>
    </div>
  {% endif %}
</div>

{% if user.is_authenticated %}
  <div class="panel panel-default">
    <div class="panel-heading">回复</div>
    <div class="panel-body">
              <form class="text" action="{% url 'question:reply' topic.id %}" method="post">
                {% csrf_token %}

                <div class="form-group">
                  <label class="sr-only" for="replay">回复</label>
                  <textarea name="content" id="reply_content" class="form-control" rows="5">{{ form.content.value |default_if_none:""}}</textarea>
                </div>

                <button type="submit" class="btn btn-default submit-btn" data-loading-text="正在提交...">回复</button>

                {% if form.content.errors %}
                <label class="pull-right">
                  <ul class="list-inline">
                  {% for item in form.content.errors %}
                      <li><p class="form-control-static text-danger">{{ item }}</p></li>
                  {% endfor %}
                  </ul>
                </label>
                {% endif %}
              </form>
    </div>
  </div>
{% endif %}
{% endblock %}
{% block footer%}
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"1","bdSize":"16"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
{% endblock %}

templates/question/topic_cell.html
{% load questiontag %}
{% load gravatar %}
<div class="cell">
  <div class="pull-left">
    <a href="{% url 'user:user' topic.author.id %}" title="{{ topic.author }}">
      <img width="48" height="48" class="headimage" src="{% gravatar topic.author 48 %}">
    </a>
  </div>
  <div class="detail">
    <div class="pull-right">
      <div class="badge badge-info">
        <a href="{% url 'question:topic' topic.id %}">
          {{ topic.num_comments }}
        </a>
      </div>
    </div>
    <a href="{% url 'question:topic' topic.id %}" class="title">
      {{topic.title}}
    </a>
    <div class="meta">
      <a href="{% url 'question:node' topic.node.slug %}" class="node">
        {{ topic.node.name }}
      </a>
      <span class="text-muted">
        •
      </span>
      <a href="{% url 'user:user' topic.author.id %}" title="{{ topic.author }}">
        {{ topic.author }}
      </a>
      <span class="text-muted">
        •
      </span>
        {{ topic.created_on|time_to_now }}
      <span class="text-muted">
        •
      </span>
        最后回复来自
      <a href="{% url 'user:user' topic.last_reply.id %}"  title="{{ topic.last_reply }}">
        {{ topic.last_reply }}  
      </a>
    </div>
  </div>
</div>