people/urls.py
from django.conf.urls import patterns, url
from people import views
import question
urlpatterns = patterns('',
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^settings/$', views.profile, name="settings"),
    url(r'^settings/upload_headimage/$', views.upload_headimage, name="upload_headimage"),
    url(r'^settings/delete_headimage/$', views.delete_headimage, name="delete_headimage"),
    url(r'^password/$', views.password, name="password"),
    url(r'^user/(?P<uid>\d+)/$', views.user, name="user"),
    url(r'^user/(?P<uid>\d+)/topics/$', views.user_topics, name="user_topics"),
    url(r'^user/(?P<uid>\d+)/comments/$', views.user_comments, name="user_comments"),
    url(r'^users/$', views.au_top, name="au_top"),
    url(r'^follow/(?P<uid>\d+)/$', views.follow, name="follow"),
    url(r'^unfollow/(?P<uid>\d+)/$', views.un_follow, name="unfollow"),
    url(r'^my/following/$', views.following, name="following"),
    url(r'^my/fav/$', question.views.fav_topic_list, name="faved_topic_list"),
    url(r'^send_verified_email/$', views.send_verified_email, name="send_verified_email"),
    url(r'^email_verified/(?P<uid>\d+)/(?P<token>\w+)/$', views.email_verified, name="email_verified"),
    url(r'^find_password/$', views.find_password, name="find_pass"),
    url(r'^reset_password/(?P<uid>\d+)/(?P<token>\w+)/$', views.first_reset_password, name="first_reset_password"),
    url(r'^reset_password/$', views.reset_password, name="reset_password"),
	)	

pro/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('question.urls', namespace='question')),
    url(r'^', include('people.urls', namespace='user')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
]

question/urls.py
from django.conf.urls import patterns, url
from question import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^recent/?$',views.recent, name='recent'),
	url(r'^node/(?P<node_slug>[\w-]+)/$',views.node,name="node"),
	url(r'^t/(?P<topic_id>\d+)/$', views.topic, name="topic"),
	url(r'^node/([\w-]+)/new/?$',views.new,name='new'),
    url(r'^t/(\d+)/edit/?$',views.edit,name='edit'),
    url(r'^t/(\d+)/reply/?$',views.reply,name='reply'),
    url(r'^t/fav/(?P<topic_id>\d+)/$', views.fav_topic, name="fav_topic"),
    url(r'^t/unfav/(?P<topic_id>\d+)/$', views.unfav_topic, name="unfav_topic"),
	url(r'^notice/?$',views.notice,name='notice'),
	url(r'^notice/(\d+)/delete/?$',views.notice_delete,name='notice_delete'),
	url(r'^about/',views.about,name='about'),
	)

people/views/follow.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from people.models import Member, Follower
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError

@csrf_protect
@login_required
def follow(request, uid):
    if request.method == "GET":
        return HttpResponseRedirect(reverse("question:index"))
        #重定向到主页，并且生成302状态码
   	#POST请求时。
    user_a = request.user
    try:
        user_b = Member.objects.get(pk=uid)
    except (Member.DoesNotExist, Follower.DoesNotExist):
        messages.error(request, "用户不存在")
        return HttpResponseRedirect(reverse("question:index"))

    if user_a.id == uid:
        messages.error(request, "不能关注自己")
        return HttpResponseRedirect(reverse("question:index"))

    try:
        follower = Follower.objects.create(user_a=user_a, user_b=user_b)
        follower.save()
        messages.success(request, u"关注用户 %s 成功" % user_b.username)
        return HttpResponseRedirect(reverse("user:user",args=(user_b.id,)))
    except IntegrityError:
        messages.error(request, u"你已经关注了用户 %s，不能重复关注" % user_b.username)
        return HttpResponseRedirect(reverse("user:user",args=(user_b.id,)))
    #一、当字段设置为唯一(unique)时，插入重复的值
	#二、如果该字段为外键，当插入一个外键，但该值在关联的表中不存时，如插入一条评论
	#评论者的id作为外键，当插入评论时，该外键去user的表格找找不到，就出现此错误
@csrf_protect
@login_required
def un_follow(request, uid):
    if request.method == "GET":
        return HttpResponseRedirect(reverse("question:index"))

    user_a = request.user
    try:
        user_b = Member.objects.get(pk=uid)
        follower = Follower.objects.filter(user_a=user_a, user_b=user_b).first()
    except (Member.DoesNotExist, Follower.DoesNotExist):
        messages.error(request, u"用户不存在")
        return HttpResponseRedirect(reverse("question:index"))
    else:
        follower.delete()
        messages.success(request, u"取消关注用户 %s 成功" % user_b.username)
        return HttpResponseRedirect(reverse("user:user",args=(user_b.id,)))

@login_required
def following(request):
    following_list = Follower.objects.filter(user_a=request.user).all()
    return render(request, "people/following.html", locals())

people/views/handle.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from people.forms import RegisterForm, LoginForm
from people.models import Member, Follower, EmailVerified as Email, FindPass
from question.models import Topic, Comment
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout, authenticate, login as auth_login
from django.utils import timezone
from django.core.cache import cache
from pro.settings import NUM_TOPICS_PER_PAGE,NUM_COMMENT_PER_PAGE
from django.conf import settings
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.mail import send_mail
import datetime


SITE_URL = getattr(settings, "SITE_URL", "http://localhost:8080")


@csrf_protect
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            #data = form.clean()
            #字段的验证方法在调用 clean() 时会运行
            data = form.cleaned_data
            new_user = Member.objects.create_user(username=data["username"],
                                                  email=data["email"],
                                                  password=data["password"])
            # Email 验证
            new_user.save()

            email_verified = Email(user=new_user)
            email_verified.token = email_verified.generate_token()
            email_verified.save()

            send_mail(u"欢迎加入", u"%s 你好：\r\n 请点击链接验证您的邮箱 %s%s" % (new_user.username,SITE_URL, reverse("user:email_verified", args=(new_user.id, email_verified.token))),
                       "18636030403@163.com", [data["email"]]
                    )
            messages.success(request, u"恭喜您注册成功，请去您的邮箱验证一下您的邮箱，如果未收到邮件，请去垃圾信箱看一下。")

            #注册成功后自动登陆
            user = authenticate(email=data["email"], password=data["password"])
            auth_login(request, user)
            go = reverse("question:index")
            #reverse使用name定义的命名空间

            # if request.session.get("next"):
            #     go = request.session.pop("next")
            # #session的工作过程
            # #生成随机字符串
            # #写到用户浏览器的cookie中
            # #保存到session中
            # #在随机字符串对应的字典中设置相关内容    

            is_auto_login = request.POST.get('auto')
            if not is_auto_login:
                request.session.set_expiry(0)
            #     #request.session.set_expiry设置session的有效期
            #     #如果value是个整数，session会在些秒数后失效。
            #     #如果value是个datatime或timedelta，session就会在这个时间后失效。
            #     #如果value是0,用户关闭浏览器session就会失效。
            #     #如果value是None,session会依赖全局session失效策略。
            return HttpResponseRedirect(go)
            #HttpResponseRedirect将客户端重定向到新的 URL。
    else:
        form = RegisterForm()
    return render(request, 'people/register.html', {
        'form': form,
        })


@csrf_protect
def login(request):
    if request.user.is_authenticated():
    	#is_authenticated：用来判断用户是否登陆
        return HttpResponseRedirect(request.META.get('HTTP_REFERER','/'))
        #HTTP Referer是header的一部分，当浏览器向web服务器发送请求的时候，一般会带上Referer
        #告诉服务器我是从哪个页面链接过来的，服务器基此可以获得一些信息用于处理。
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            # 邮箱
            username = data["username"]
            if '@' in username:
                email = username
            else:
                user = Member.objects.get(username=username)
                email = user.email
            user = authenticate(email=email, password=data["password"])
            #密码有效返回User对象
            #密码无效返回None
            if user is not None:
                auth_login(request, user)
                go = reverse("question:index")
                 
                # if request.session.get("next"):
                #     go = request.session.pop("next")

                is_auto_login = request.POST.get('auto')
                if not is_auto_login:
                    request.session.set_expiry(0)
                return HttpResponseRedirect(go)
            else:
                messages.error(request, '密码不正确！')
                return render(request,'people/login.html',locals())
    else:
        form = LoginForm()

    # if request.GET.get("next"):
    #     request.session["next"] = request.GET["next"]

    return render(request, 'people/login.html', {
        'form': form
        })

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('question:index'))

#用户信息
def user(request, uid):
    user_from_id = Member.objects.get(pk=uid)
    user_a = request.user
    if user_a.is_authenticated():
        try:
            follower = Follower.objects.filter(user_a=user_a, user_b=user_from_id).first()
        except (Member.DoesNotExist, Follower.DoesNotExist):
            follower = None

    topic_list = Topic.objects.order_by("-created_on").filter(author=user_from_id.id)[:10]
    comment_list = Comment.objects.order_by("-created_on").filter(author=user_from_id)[:10]
    return render(request, "people/user.html", locals())

#用户榜
def au_top(request):
    au_list = cache.get('au_top_list')
    if not au_list:
        au_list = Member.objects.order_by('-au')[:20]
        cache.set('au_top_list',au_list,600)

    user_count = cache.get('user_count')
    if not user_count:
        user_count = Member.objects.all().count()
        cache.set('user_count',user_count,600)

    return render(request, "people/au_top.html", locals())

#用户发表文章
def user_topics(request, uid):
    this_user = Member.objects.get(pk=uid)
    topic_list = Topic.objects.order_by("-created_on").filter(author=uid)
    paginator = Paginator(topic_list, NUM_TOPICS_PER_PAGE)
    page = request.GET.get('page')
    try:
        topic_list = paginator.page(page)
    except PageNotAnInteger:
        topic_list = paginator.page(1)
    except EmptyPage:
        topic_list = paginator.page(paginator.num_pages)

    return render(request, "people/user_topics.html", locals())
    
# 用户个人页面 - 所有回复
def user_comments(request, uid):
    this_user = Member.objects.get(pk=uid)
    comment_list = Comment.objects.order_by("-created_on").filter(author=uid)
    paginator = Paginator(comment_list, NUM_COMMENT_PER_PAGE)
    page = request.GET.get('page')
    try:
        comment_list = paginator.page(page)
    except PageNotAnInteger:
        comment_list = paginator.page(1)
    except EmptyPage:
        comment_list = paginator.page(paginator.num_pages)

    return render(request, "people/user_comments.html", locals())
#邮箱验证功能
@login_required
@csrf_protect
def send_verified_email(request):
    if request.method == "GET":
        return HttpResponseRedirect(reverse("user:settings"))

    user = request.user
    if user.email_verified:
        messages.error(request, u"您的邮箱已经验证过了")
        return HttpResponseRedirect(reverse("user:settings"))

    last_email = None
    try:
        last_email = Email.objects.get(user=user)
    except:
        pass

    if last_email and (timezone.now() - last_email.timestamp).seconds < (60):
        messages.error(request, u'一分钟内只能申请验证一次哦！')
    else:
        try:
            email = Email.objects.get(user=user)
            email.token = email.generate_token()
            email.timestamp = timezone.now()
            email.save()
        except Email.DoesNotExist:
            email = Email(user=user)
            email.token = email.generate_token()
            email.save()
        finally:
            send_mail(u"欢迎加入!", u"%s 你好：\r\n 欢迎您注册成为会员,请点击链接验证您的邮箱: %s%s" % 
                        (user.username,SITE_URL, reverse("user:email_verified", args=(user.id, email.token))),
                        "18636030403@163.com", [user.email]
                    )
            messages.success(request, u"邮件已经发送，请去您的邮箱验证一下您的邮箱，如果未收到邮件，请去垃圾信箱看一下。")
    return HttpResponseRedirect(reverse("user:settings"))

def email_verified(request, uid, token):
    try:
        user = Member.objects.get(pk=uid)
        email = Email.objects.get(user=user)
    except Member.DoesNotExist:
        raise Http404
    except Email.DoesNotExist:
        raise Http404
    else:
        if email.token == token:
            user.email_verified = True
            user.save()
            email.delete()
            messages.success(request, u"验证成功")
            if not request.user.is_authenticated():
                auth_login(request, user)
            return HttpResponseRedirect(reverse("question:index"))
        else:
            raise Http404


#邮件找回密码功能
def find_password(request):
    if request.method == "GET":
        return render(request, "people/find_password.html")

    email = request.POST["email"]
    user = None
    try:
        user = Member.objects.get(email=email)
    except Member.DoesNotExist:
        messages.error(request, '未找到用户')
    
    if user:
        find_pass = FindPass.objects.filter(user=user)
        if find_pass:
            find_pass = find_pass[0]
            if (timezone.now() - find_pass.timestamp).seconds < (60):
                messages.error(request, '一分钟内不能重复找回密码')
                return HttpResponseRedirect(reverse("question:index"))
        else:
            find_pass = FindPass(user=user)
            find_pass.timestamp = timezone.now()
            find_pass.token = find_pass.generate_token()

        find_pass.save()
        send_mail(u"重置密码", u"%s 你好：\r\n 请点击链接重置密码 %s%s" % (user.username,SITE_URL, reverse("user:first_reset_password", args=(user.id, find_pass.token))),
            "18636030403@163.com", [email]
                )
        messages.success(request, u"找回密码邮件已经发送，邮箱如果未收到邮件，请去垃圾信箱看一下。")
    
    return HttpResponseRedirect(reverse("question:index"))

def first_reset_password(request, uid=None, token=None):
    user = Member.objects.get(pk=uid)

templates/people/find_password.html
{% extends "base.html" %}

{% block title %}找回密码 - {% endblock %}

{% load humanize %}

{% block content %}
            <div class="panel panel-default">
              <div class="panel-heading">找回密码</div>
              <div class="panel-body">
                    <form class="form-horizontal" action="{% url 'user:find_pass' %}" method='POST'>
                      {% csrf_token %}
                    <div class="form-group">
                        <label for="" class="col-sm-3 control-label">邮箱：</label>
                        <div class="col-sm-5">
                          <input type="email" class="form-control" name="email" value="">
                        </div>
                    </div>
                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-10">
                            <button type="submit" class="btn btn-default">发送邮件</button>
                          </div>
                        </div>
                    </form>
                </div>
              </div>
{% endblock %}

templates/people/login.html
{% extends "base.html" %}

{% block title %}登陆 - {% endblock %}

{% load humanize %}

{% block content %}
            <div class="panel panel-default">
              <div class="panel-heading">登陆</div>
              <div class="panel-body">
                    <form class="form-horizontal" action="{% url 'user:login' %}" method='POST'>
                      {% csrf_token %}
                    {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id }}" class="col-sm-3 control-label">{{ field.label }}：</label>
                        <div class="col-sm-5">
                          <input type="{% if forloop.counter == 1 %}text{% elif forloop.counter == 2 %}password{% endif %}" class="form-control" name="{{ field.html_name }}" value="{{ field.value |default_if_none:""}}">
                          {% if field.help_text %}
                            <span class="help-block">{{field.help_text}}</span>
                          {% endif %}
                        </div>
                        {% if field.errors %}
                        <label>
                          <ul class="list-inline">
                          {% for item in field.errors %}
                              <li><p class="form-control-static text-danger">{{ item }}</p></li>
                          {% endfor %}
                          </ul>
                        </label>
                        {% endif %}
                    </div>
                    {% endfor %}
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                            <div class="checkbox">
                                <label>
                                <input type="checkbox" name="auto" > 记住我 
                                </label>
                                <a style="margin-left:50px;" href="{% url 'user:find_pass' %}">忘记密码</a>
                            </div>
                            </div>
                        </div>
                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-10">
                            <button type="submit" class="btn btn-default">登陆</button>
                          </div>
                        </div>

                    </form>
                </div>
              </div>
{% endblock %}

templates/people/password.html
{% extends "base.html" %}

{% block title %}修改密码 - {% endblock %}

{% load humanize %}

{% block content %}
            <div class="panel panel-default">
              <div class="panel-heading">修改密码</div>
              <div class="panel-body">
                  <form action="{% url 'user:password' %}" method='POST' class="form-horizontal">{% csrf_token %}
                  {% for field in form %}
                  <div class="form-group">
                      <label for="{{ field.id }}" class="col-sm-2 control-label">{{ field.label }}：</label>
                      <div class="col-sm-4">
                        {{ field }}
                        {% if field.help_text %}<span class="help-block">{{field.help_text}}</span>{% endif %}
                      </div>
                        {% if field.errors %}
                            <label>
                              <ul class="list-inline">
                                {% for item in field.errors %}
                                    <li><p class="form-control-static text-danger">{{item}}</p></li>
                                {% endfor %}
                              </ul>
                            </label>
                      {% endif %}
                  </div>
                  {% endfor %}
                <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-default">修改</button>
                          </div>
                        </div>
                </form>
              </div>
            </div>
{% endblock %}

templates/people/register.html
{% extends "base.html" %}

{% block title %}注册 - {% endblock %}

{% load humanize %}

{% block content %}
              <div class="panel panel-default">
                <div class="panel-heading">注册</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="{% url 'user:register' %}" method="POST">
                      {% csrf_token %}
                      {% for field in form %}
                      <div class="form-group">
                        <label for="{{ field.id }}" class="col-sm-3 control-label">{{ field.label }}：</label>
                        <div class="col-sm-5">
                          <input type="{%if forloop.counter == 1 %}text{% elif forloop.counter == 2 or forloop.counter == 3 %}password{% elif forloop.counter == 4 %}email{% endif %}" class="form-control" name="{{ field.html_name }}" value="{{ field.value |default_if_none:""}}">
                          {% if field.help_text %}
                            <span class="help-block">{{field.help_text}}</span>
                          {% endif %}
                        </div>
                        <div class="col-sm-4">
                          {% if field.errors %}
                            <label>
                              <ul class="list-inline">
                              {% for item in field.errors %}
                                  <li><p class="form-control-static text-danger">{{item}}</p></li>
                              {% endfor %}
                              </ul>
                            </label>
                        {% endif %}
                        </div>
                      </div>
                      {% endfor %}
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-default">注册</button>
                        </div>
                      </div>
                    </form>
                  </div>
              </div>
{% endblock %}

templates/people/settings.html
<meta charset="utf-8">
{% extends "base.html" %}

{% block title %}设置 - {% endblock %}

{% load humanize %}
{% load gravatar %}

{% block content %}
{% if not user.is_email_verified %}
<form id="send_email_form" action="{% url 'user:send_verified_email' %}" method='POST'>{% csrf_token %}
<script>
    $(function(){
            $("#send_verified_email").click(function(){
            $("#send_email_form").submit()
            });
    });
</script>
</form>

{% endif %}
            <div class="panel panel-default">
                <div class="panel-heading">个人设置
{% if not user.is_email_verified %}
                    <a href="#" id="send_verified_email" class="btn btn-info btn-xs pull-right">验证邮箱</a>
{% endif %}
                </div>
                <div class="panel-body">
                  <form action="{% url 'user:settings' %}" method='POST' class="form-horizontal">{% csrf_token %}
                  {% for field in form %}
                  <div class="form-group">
                      <label for="{{ field.id }}" class="col-sm-3 control-label">{{ field.label }}：</label>
                      <div class="col-sm-5">
                      {% if forloop.counter == 2 %}
                        <div class="input-group">
                          <span class="input-group-addon">weibo.com/</span>
                          <input type="text" class="form-control" name="{{ field.html_name }}" value="{{ field.value }}">
                        </div>
                      {% elif forloop.counter == 3 %}
                        <div class="input-group">
                          <span class="input-group-addon">http://</span>
                          <input type="text" class="form-control" name="{{ field.html_name }}" value="{{ field.value }}">
                        </div>
                      {% else %}
                          {{ field }}
                      {% endif %}
                      {% if field.help_text %}<span class="help-block">{{ field.help_text }}</span>{% endif %}
                      </div>
                      {% if field.errors %}
                      <label>
                        <ul class="list-inline">
                        {% for item in field.errors %}
                            <li><p class="form-control-static text-danger">{{ item }}</p></li>
                        {% endfor %}
                        </ul>
                      </label>
                      {% endif %}
                  </div>
                  {% endfor %}
                        <div class="form-group">
                          <div class="col-sm-offset-3 col-sm-10">
                            <button type="submit" class="btn btn-default">修改</button>
                          </div>
                        </div>
                </form>
                </div>
              </div>
            <div class="panel panel-default">
                <div class="panel-heading">头像设置
                    <a href="{% url 'user:delete_headimage' %}" class="btn btn-warning btn-xs pull-right">删除头像</a>
              </div>
                <div class="panel-body headimage_setting">
                    <!-- upload -->
                    <form class="form-horizontal" method="post" action="http://up-z2.qiniu.com/" enctype="multipart/form-data">
                      <input name="key" type="hidden" value="avatar/{{ user.username }}">
                      <input name="token" type="hidden" value="{{uptoken}}">
                      
                      <div class="form-group">
                        <label class="col-xs-4 col-sm-3 control-label">当前头像：</label>
                        <div class="col-xs-8 col-sm-3"><img  width="48" height="48" src="{% gravatar user 48 %}" /></div>
                      </div>

                      <div class="form-group">
                        <label class="col-xs-4 col-sm-3 control-label">选择一张图片：</label>
                        <input class="col-xs-8 col-sm-8 file_input" name="file" type="file" accept="image/jpeg, image/png" />
                      </div>
                      <div class="form-group">
                        <label class="col-xs-4 col-sm-3"></label>
                        <span class="help-block col-xs-8 col-sm-8">上传限制：PNG/JPG 300KB (未上传则自动抓取邮箱对应<a href="http://cn.gravatar.com" target="_blank">Gravatar头像</a>)</span>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-10">
                          <button type="submit" class="btn btn-default">上传</button>
                        </div>
                      </div>
                    </form>
                    <!-- upload -->
                  </div>
            </div>
{% endblock %}

templates/people/user.html
{% extends "base.html" %}

{% block title %}{{ user_from_id.username }} - {% endblock %}

{% load humanize %}
{% load gravatar %}
{% load questiontag %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-body userpage">
        <div class="row">
            <div class="col-md-3">
                <img width="120" height="120" src="{% gravatar user_from_id 120 %}" class="img-responsive center-block" alt="{{ user_from_id.username }}">
            </div>
            <div class="col-md-9">
                <strong class="username">{{ user_from_id.username }}</strong>
                {% if user.is_authenticated %}
                {% if user_a.id != user_from_id.id %}
                <div class="pull-right">
                    {% if not follower %}
                    <form action="{% url 'user:follow' user_from_id.id %}" method=POST>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default">关注</button>
                    </form>
                    {% else %}
                    <form action="{% url 'user:unfollow' user_from_id.id %}" method=POST>
                        {% csrf_token %}
                        <button type="submit" class="btn btn-default">取消关注</button>
                    </form>
                    {% endif %}
                </div>
                {% endif %}
                {% endif %}
                <p>你是第 {{ user_from_id.id }} 名会员，加入于 {{ user_from_id.date_joined|date:'Y-m-d H:i:s' }}</p>
            </div>
            <div class="col-md-12 p-info">
            </br>
            {% if user_from_id.location %}
                <p> <strong>位置：</strong>{{ user_from_id.location }}</p>
            {% endif %}
            {% if user_from_id.weibo_id %}
                <p> <strong>微博：</strong><a href="http://weibo.com/{{ user_from_id.weibo_id }}" target='_blank'>{{ user_from_id.weibo_id }}</a></p>
            {% endif %}
            {% if user_from_id.blog %}
                <p> <strong>博客：</strong><a href="http://{{ user_from_id.blog }}" target='_blank'>{{ user_from_id.blog }}</a></p>
            {% endif %}
            {% if user_from_id.profile %}
                <blockquote class="pull-right">
                  <p>{{ user_from_id.profile }}</p>
                  <small>{{ user_from_id.username }}</small>
                </blockquote>
            {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">最近创建的主题</div>
  <div class="panel-body tableview">
    {% for topic in topic_list %}
        {% include "people/user_topics_cell.html" %}
    {% endfor %}
    </div>
    <div class="panel-footer">
        <a href="{% url 'user:user_topics' user_from_id.id %}">» {{ user_from_id.username }} 创建的更多主题</a>
    </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">最近回复的主题</div>
  <div class="panel-body comment-tableview">
    {% for comment in comment_list %}
        {% include "people/user_comments_cell.html" %}
    {% endfor %}
  </div>
    <div class="panel-footer">
        <a href="{% url 'user:user_comments' user_from_id.id %}">» {{ user_from_id.username }} 创建的更多回复</a>
    </div>
</div>

{% endblock %}

templates/people/user_topics_cell.html
{% load questiontag %}
    <div class="cell">
        <div class="detail" style="padding-left:0px;">
            <div class="pull-right">
                <div class="badge badge-info">
                    <a href="{% url 'question:topic' topic.id %}">
                        {{ topic.num_comments }}
                    </a>
                </div>
            </div>
            <a href="{% url 'question:topic' topic.id %}" class="title">
                {{topic.title}}
            </a>
            <div class="meta">
                <a href="{% url 'question:node' topic.node.slug %}" class="node">
                    {{ topic.node.name }}
                </a>
                <span class="text-muted">
                    •
                </span>
                <a href="{% url 'user:user' topic.author.id %}" title="{{ topic.author }}">
                    {{ topic.author }}
                </a>
                <span class="text-muted">
                    •
                </span>
                {{ topic.created_on|time_to_now }}
                <span class="text-muted">
                    •
                </span>
                最后回复来自
                <a href="{% url 'user:user' topic.last_reply.id %}"  title="{{ topic.last_reply }}">
                    {{ topic.last_reply }}
                </a>
            </div>
        </div>
    </div>