people/urls.py
from django.conf.urls import patterns, url
from people import views
import question
urlpatterns = patterns('',
    url(r'^register/$', views.register, name="register"),
    url(r'^login/$', views.login, name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^settings/$', views.profile, name="settings"),
    url(r'^settings/upload_headimage/$', views.upload_headimage, name="upload_headimage"),
    url(r'^settings/delete_headimage/$', views.delete_headimage, name="delete_headimage"),
    url(r'^password/$', views.password, name="password"),
    url(r'^user/(?P<uid>\d+)/$', views.user, name="user"),
    url(r'^user/(?P<uid>\d+)/topics/$', views.user_topics, name="user_topics"),
    url(r'^user/(?P<uid>\d+)/comments/$', views.user_comments, name="user_comments"),
    url(r'^users/$', views.au_top, name="au_top"),
    url(r'^follow/(?P<uid>\d+)/$', views.follow, name="follow"),
    url(r'^unfollow/(?P<uid>\d+)/$', views.un_follow, name="unfollow"),
    url(r'^my/following/$', views.following, name="following"),
    url(r'^my/fav/$', question.views.fav_topic_list, name="faved_topic_list"),
    url(r'^send_verified_email/$', views.send_verified_email, name="send_verified_email"),
    url(r'^email_verified/(?P<uid>\d+)/(?P<token>\w+)/$', views.email_verified, name="email_verified"),
    url(r'^find_password/$', views.find_password, name="find_pass"),
    url(r'^reset_password/(?P<uid>\d+)/(?P<token>\w+)/$', views.first_reset_password, name="first_reset_password"),
    url(r'^reset_password/$', views.reset_password, name="reset_password"),
	)	

pro/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('question.urls', namespace='question')),
    url(r'^', include('people.urls', namespace='user')),
    url(r'^sites/', include('sites.urls', namespace='sites')),
]

question/urls.py
from django.conf.urls import patterns, url
from question import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^recent/?$',views.recent, name='recent'),
	url(r'^node/(?P<node_slug>[\w-]+)/$',views.node,name="node"),
	url(r'^t/(?P<topic_id>\d+)/$', views.topic, name="topic"),
	url(r'^node/([\w-]+)/new/?$',views.new,name='new'),
    url(r'^t/(\d+)/edit/?$',views.edit,name='edit'),
    url(r'^t/(\d+)/reply/?$',views.reply,name='reply'),
    url(r'^t/fav/(?P<topic_id>\d+)/$', views.fav_topic, name="fav_topic"),
    url(r'^t/unfav/(?P<topic_id>\d+)/$', views.unfav_topic, name="unfav_topic"),
	url(r'^notice/?$',views.notice,name='notice'),
	url(r'^notice/(\d+)/delete/?$',views.notice_delete,name='notice_delete'),
	url(r'^about/',views.about,name='about'),
	)

sites/urls.py
from django.conf.urls import patterns, url
from sites import views

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	)

templates/base.html
{% load questiontag %}
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta name="description" content="问答社区">
    <title>{% block title %}{% endblock %}主页</title>
    <link href="http://cdn.staticfile.org/twitter-bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <script src="http://cdn.staticfile.org/jquery/2.1.0/jquery.min.js"></script>
    <script src="http://cdn.staticfile.org/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="{% static "js/main.js" %}"></script>
  </head>

  <body>
    <!-- Wrap all page content here -->
    <div id="wrap">
      <!-- Fixed navbar -->
      <div class="navbar navbar-default navbar-static-top " role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">
                Toggle navigation
              </span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">主页</a>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="/">首页</a></li>
              <li><a href="{% url 'sites:index' %}">酷站</a></li>
              <li><a href="{% url 'user:au_top' %}">用户榜</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                <li><a href="{% url 'user:user' user.id %}">个人主页</a></li>
                <li><a href="{% url 'user:password' %}">修改密码</a></li>
                <li><a href="{% url 'user:settings' %}">设置</a></li>
                <li><a href="{% url 'user:logout' %}">登出</a></li>
              {% else %}
                <li><a href="{% url 'user:login' %}?next={{request.path}}">登陆</a></li>
                <li><a href="{% url 'user:register' %}">注册</a></li>
              {% endif %}
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>

      <!-- Begin page content -->
      <div class="container">
        <div class="row">
          <div class="col-xs-12 col-sm-7 col-md-8">  
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-warning fade in">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            {% block content %}
            {% endblock %}
            {% block reply %}
            {% endblock %}
          </div>
          <div class="col-xs-12 col-sm-5 col-md-4">
            <div class="panel panel-default hidden-xs userinfo">
              {% if user.is_authenticated %}
                <div class="panel-body">
                  <div class="box-content userinfo">
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                      <tbody>
                        <tr>
                          <td width="48" valign="top">
                            <a href="{% url 'user:user' user.id %}">
                              {% load gravatar %}
                            <img width="48" height="48" src="{% gravatar user 48 %}" class="avatar" border="0" align="default"></a>
                          </td>
                          <td width="10" valign="top"></td>
                          <td width="auto" align="left">
                            <span class="username">
                              <a href="{% url 'user:user' user.id %}">
                                {{ user.username }}
                              </a>
                            </span>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <table cellpadding="0" cellspacing="0" border="0" width="100%">
                      <tbody>
                        <tr>
                          <td width="50%" class="td-line" align="center">
                            <a href="{% url 'user:faved_topic_list' %}" class="dark" style="display: block;">
                              <span>{% get_fav_count user %}</span></br>
                              <span>收藏</span></a>
                          </td>
                          <td width="50%" align="center">
                            <a href="{% url 'user:following' %}" class="dark" style="display: block;">
                              <span>
                                {% get_following_count user %}
                              </span>
                              </br>
                              <span >关注</span>
                            </a>
                          </td>
                        </tr>
                      </tbody>
                    </table>
                    <div class="box-line">
                    </div>
                    <div class="panel-footer notice">
                      <a href="{% url 'question:notice' %}">
                        {% num_notice user as unread_notice_cnt %}
                          {% if unread_notice_cnt != 0 %}
                            {{ unread_notice_cnt }} 条未读信息
                          {% else %}
                            暂无未读消息
                          {% endif %}
                      </a>
                    </div>
                  </div>
                </div>
                {% else %}
                  <div class="panel-heading">登陆</div>
                  <div class="panel-body">
                    <div class="center">
                      <p><a href="{% url 'user:register' %}" class="btn btn-default">现在注册</a></p>
                      <p>已注册用户请 <a href="{% url 'user:login' %}">登陆</a></p>
                    </div>
                  </div>
                {% endif %}

            </div>
              {% block sidebar %} {% endblock %}
          </div>
        </div>
      </div>
    </div>
      <div id="footer">
        <div class="container">
          <p class="text-muted">Think Different <span class="pull-right"><a href="/about">关于</a></span></p>
        </div>
      </div>
      {% block footer%}{% endblock %}
  </body>
</html>